import React from "react";

export const guideHeadings: Record<string, string[]> = {
  "after-rain-roof-leak-check-canberra": ["Start with a record of the leak", "Record indoor signs and rain timing", "Describe the roof area from the ground", "Prepare your roof leak enquiry"],
  "cracked-slipped-missing-roof-tiles-canberra": ["Can damaged tiles be repaired locally?", "Record the location of visible tile damage", "Include indoor signs and previous repairs", "Prepare a tile roof repair enquiry"],
  "chimney-flashing-water-entry-signs": ["Start with the chimney-to-roof junction", "Record water marks near the chimney", "Describe visible changes from the ground", "Prepare a chimney flashing enquiry"],
  "rebedding-vs-repointing-canberra-roofs": ["What bedding and pointing do", "Rebedding versus repointing", "Record the ridge lines that concern you", "Prepare a ridge capping repair enquiry"],
  "when-to-arrange-roof-inspection-canberra": ["When a roof inspection helps", "Record the reason for your inspection", "Prepare photographs without roof access", "Arrange the inspection and agree its scope"],
};

const planning: Record<string, { heading: string; text: string; question: string; answer: string }> = {
  "roof-leak-repairs": { heading: "Arrange an investigation before choosing a leak repair", text: "A fresh stain and a recurring leak both need a clear account of where and when water appears. Include previous repairs so we can assess the affected area and discuss the work needed before you approve a quote.", question: "What should I send if the leak only appears in heavy rain?", answer: "Record the affected room, when the drip starts, how long it lasts and the weather at the time. Mention any previous work at that location. These details help prepare the investigation; the repair scope follows the on-site findings." },
  "tile-roof-repairs": { heading: "Compare a local tile repair with wider roof work", text: "Tell us if you have noticed one damaged tile or several affected areas. We assess the surrounding roof condition and available replacement materials before recommending local repairs or discussing a broader renovation scope.", question: "What should a quote for a few damaged tiles explain?", answer: "Ask which roof area and tiles are included, how suitable replacement materials will be selected, and whether adjoining ridge or flashing repairs are needed. Confirm access and any inspection fee before arranging the visit." },
  "chimney-flashing-repairs": { heading: "Book an assessment of the chimney junction", text: "Describe the room or wall where water appears and the nearby chimney area. Our service focuses on the chimney-to-roof junction and connected roof repairs; discuss any separate chimney concern when agreeing the inspection scope.", question: "Should I request flashing work before the junction is inspected?", answer: "Start by describing the water mark or visible change. Ellis checks the junction and adjoining materials before confirming which flashing or connected repairs belong in the quote." },
  "rebedding-repointing": { heading: "Choose ridge repairs from the condition found", text: "Surface pointing and the bedding beneath ridge caps are assessed together. Ask which ridge or hip lines need attention and why, so the quote distinguishes the proposed rebedding, repointing and connected tile work.", question: "Does every ridge line need the same work?", answer: "The scope follows the condition found on site. Describe whether the visible concern is limited to one area or extends across several roof lines; Ellis explains the areas and work included in the quote." },
  "roof-inspections": { heading: "Agree the inspection purpose before booking", text: "Tell us whether you need help with a leak, a visible defect or maintenance planning. Confirm the appointment scope, available access, inspection fee and the findings to be provided before the visit.", question: "Can I book an inspection without choosing a repair service?", answer: "Yes. Describe your concern and suburb, even if you do not know the roof material or cause. We agree the inspection scope, assess the relevant areas and explain the repair options and written quote." },
  "metal-roof-repairs": { heading: "Discuss repair options for your metal roof", text: "Describe the affected sheets or junction, the indoor signs and any previous work. The inspection considers the existing material and adjoining details so the quote identifies the proposed repair area rather than assuming the whole roof needs replacement.", question: "What information helps with a metal or Colorbond roof quote?", answer: "Include the roof material if known, where the concern appears, when it occurs and previous repairs. Ask which sheets, fasteners or junctions are included in the recommended work and what further assessment may be needed." },
  "roof-renovation": { heading: "Repair, renovation or replacement: compare the scope", text: "An isolated defect, repeated problems across several areas and a goal to refresh the roof call for different discussions. Compare the extent of defects, existing material condition, previous repairs and your plans for the property. Ask what local repair would address, what renovation adds and which concerns would remain. If replacement is being considered, clarify that scope separately before making a decision.", question: "How can I compare renovation with repairing the affected area?", answer: "Ask for the defects identified, the repairs needed before any finish work, the roof areas included and any limitations of the proposed approach. Compare the scope and materials, rather than treating a surface refresh as the answer to every roof concern." },
  "roof-cleaning": { heading: "Confirm cleaning and repair requirements separately", text: "Describe whether your priority is surface build-up, appearance or a water-entry concern. The quote should identify the roof areas to be cleaned, the proposed method and any repair or drainage work discussed after assessment.", question: "What should I confirm before booking roof cleaning?", answer: "Confirm the roof material, areas included, suitable cleaning approach, access and drainage arrangements. Mention any known leak or damaged material so Ellis can discuss the repair requirements alongside the cleaning scope." },
  "gutter-downpipe-maintenance": { heading: "Plan the work around the reported overflow", text: "Tell us which roof edge or downpipe concerns you and when overflow occurs. We assess the drainage route and explain whether the proposed work is clearing, maintenance or repair, with the included areas shown in the quote.", question: "What should a gutter and downpipe maintenance quote include?", answer: "Ask which gutter runs, outlets and downpipes are included, how access will be arranged and whether any component repairs are priced separately. Include indoor water signs so connected roof concerns can also be discussed." },
};

export function ServicePlanning({ slug }: { slug: string }) {
  const item = planning[slug];
  return item ? <section className="contentGuidance servicePlanning"><h2>{item.heading}</h2><p>{item.text}</p><p>Use our <a href="/news/when-to-arrange-roof-inspection-canberra">inspection and repair quote checklist</a> to prepare the details for your visit.</p></section> : null;
}

export function ServiceBookingFaq({ slug }: { slug: string }) {
  const item = planning[slug];
  return item ? <details><summary>{item.question}</summary><p>{item.answer}</p></details> : null;
}

export function EnquiryChecklist() {
  return <section className="contentGuidance enquiryChecklist"><h2>What to prepare for an inspection and quote</h2><ul><li>Your suburb, property address and preferred contact details.</li><li>The affected room or roof area, when the issue started and whether it follows rain.</li><li>Roof material if known, previous repairs and optional photos from a safe position.</li><li>Property access, number of storeys and who can authorise the work.</li></ul><p>Before booking, confirm the appointment, any inspection or booking fee, access and the findings to be provided. For a repair quote, ask which roof areas, components and materials are included, which items are excluded and whether further investigation is needed. Agree the work and price before repairs begin.</p><p>See <a href="/news/when-to-arrange-roof-inspection-canberra">how an inspection becomes a repair scope</a>, or <a href="/services">compare the roof services</a> if you are unsure where to start.</p></section>;
}

export function GuideNextSteps({ slug }: { slug: string }) {
  const tile = slug === "cracked-slipped-missing-roof-tiles-canberra";
  const ridge = slug === "rebedding-vs-repointing-canberra-roofs";
  const chimney = slug === "chimney-flashing-water-entry-signs";
return <section className="contentGuidance guideNextSteps"><h2>{tile || ridge ? "Decide between local repair and wider roof work" : "Connect your observations to the next step"}</h2><p>{tile ? "A visible tile defect is a starting point for a local repair assessment. The number of affected areas, condition of neighbouring materials, available replacement tiles and previous repairs help shape the scope. Ask what the proposed repair will address before deciding whether a broader renovation is appropriate." : ridge ? "Ask whether the concern is confined to particular ridge or hip lines, what condition the supporting bedding is in and which adjoining tiles need attention. A quote should distinguish the ridge work from any broader renovation. A worn appearance alone does not decide the scope." : chimney ? "A water mark near a chimney gives the inspection a location to investigate, rather than a confirmed flashing diagnosis. Include the weather pattern and previous patching so the junction and connected roof details can be discussed together. Ask which components are included in the recommended repair." : "Your notes help Ellis prepare for the visit; the inspection connects those observations to the roof condition and proposed work. If the concern has returned, include the dates and location of previous repairs so the next discussion starts with that history."}</p><p>For {tile || ridge ? <>a wider roof refresh, compare the <a href="/services/roof-renovation">roof renovation assessment</a> with the local repair scope. Consider the extent of defects, existing material condition and your plans for the property before discussing renovation or replacement.</> : slug === "after-rain-roof-leak-check-canberra" ? <>inspection and quote preparation, read the <a href="/news/when-to-arrange-roof-inspection-canberra">roof inspection guide</a>. If the starting point is unclear, explore <a href="/services/roof-inspections">roof inspections</a>.</> : <>help recording rain timing, read the <a href="/news/after-rain-roof-leak-check-canberra">after-rain leak guide</a>. If the starting point is unclear, explore <a href="/services/roof-inspections">roof inspections</a>.</>}</p><h2>Related guides for your enquiry</h2><ul>{slug !== "when-to-arrange-roof-inspection-canberra" && <li><a href="/news/when-to-arrange-roof-inspection-canberra">Roof inspection preparation and written repair quotes</a></li>}{slug !== "cracked-slipped-missing-roof-tiles-canberra" && <li><a href="/news/cracked-slipped-missing-roof-tiles-canberra">Recording cracked, slipped or missing roof tiles</a></li>}{slug !== "rebedding-vs-repointing-canberra-roofs" && <li><a href="/news/rebedding-vs-repointing-canberra-roofs">Understanding rebedding and repointing</a></li>}</ul><p><a href="/contact">Send Ellis Services Group your suburb and roof concern</a> to arrange an assessment. A photo is optional.</p></section>;
}

export function LocalGuideLinks() {
  return <section className="contentGuidance localGuideLinks"><h2>Prepare for a roof assessment in your area</h2><p>Your address and the actual roof concern help us plan the visit. Include the affected area, timing, known previous repairs and access arrangements when you enquire.</p><p>Read the <a href="/news/after-rain-roof-leak-check-canberra">after-rain roof leak guide</a> for observation notes, or the <a href="/news/when-to-arrange-roof-inspection-canberra">inspection and quote preparation guide</a> before booking. You can also <a href="/services">compare all roof repair and maintenance services</a>.</p></section>;
}
